<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Async JavaScript</title>
</head>

<body>
    <h1>Async & Await in JavaScript</h1>
    <!--     
        Async functions always return a "Promise" 

        Promise is either resolved or rejected 
        if "resolved ---- .then()", "if reject ---- .catch()" 
     -->

    <script>
        // async function test() {
        //     return "Hello";
        // }
        // test().then((result) => {
        //     console.log(result);
        // })

        //---------------------- AWAIT -----------------------------
        // async function test(){
        //     console.log("2 : message");
        //     await console.log("3 : message");
        //     console.log("4 : message");
        // }
        // console.log("1 : message");
        // test();
        // console.log("5 : message");

        //------------------------------------------------------------
        async function test() {
            const response = await fetch("/Async-Await-js/student_data.json");
            const students = await response.json();

            return students;
        }
        test().then((result) => {
            console.log(result);
        })
        .catch((error) => {  // instead of writing catch for every specific "then" statements, we can put above async code in try-catch, where in the catch part we can write this line 47-50
            console.log(error);
        })


    </script>
</body>

</html>